### ISSUE TITLE
建议去掉海报里的[center][/center]代码

### ISSUE THREAD

**Issue by ylxb2016** [BFDZ/PT-Gen#4]
BFDZ大佬好，你的https://www.bfdz.ink/tools/ptgen  很好，一直在用。
不过想提个小建议，

1.  不知道可否去掉海报里的[center][/center]代码，好多站点的bbcode并不支持这个center，每次需要手动删除这段代码

1. 测试了很多次，https://img3.hongleyou.cn 这个图床没有 img1.doubanio.com 加载快。

**Comment by BFDZ** [comment]
1、主流的nexusphp程序均支持 center 标签
2、图床已经换回豆瓣了

**Comment by ylxb2016** [comment]
谢谢BFDZ大佬的答复，
关于1，因为不少人也会在论坛上用，部分nexusphp站点对center支持也不好，所以去掉的话，适用性会更广一些，我看到不少人都在用大佬这个工具，然后手动删掉center。

**Comment by ylxb2016** [comment]
@BFDZ 另外，要是可以自动把img3替换为img1就更完美了，img3好多时候没法直接引用（加载不出来图像）比如https://img3.doubanio.com/view/photo/l_ratio_poster/public/p1863974996.jpg 换为 https://img1.doubanio.com/view/photo/l_ratio_poster/public/p1863974996.jpg

**Comment by BFDZ** [comment]
img3可能是豆瓣做了限制，这个问题会更新解决
